DEFAULT_PASSWORD_LENGTH = 12

LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'
UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS = '0123456789'
SPECIAL = '!@#$%^&*()_+-=[]{}|;:,.<>?'

DEFAULT_CHARSET = LOWERCASE + UPPERCASE + DIGITS