DEFAULT_PASSWORD_LENGTH = 12

LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'
UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS = '0123456789'
SPECIAL = '!@#$%^&*()_+-=[]{}|;:,.<>?'

MIN_COMPLEX_LENGTH = 12
RECOMMENDED_COMPLEX_LENGTH = 16
REQUIRE_ALL_CHAR_TYPES = True 

DEFAULT_CHARSET = LOWERCASE + UPPERCASE + DIGITS